### ISSUE TITLE
Possible to use GFA 1.0 as input to gaftools index?

### ISSUE THREAD

**Issue by adadiehl** [marschall-lab/gaftools#19]
I would like to use this toolkit within an analysis workflow I am developing. The nature of the analysis requires the graph be in GFA 1.0 format for reasons I won't go into. However, supplying a GFA 1.0 as input to ```gaftools index``` causes a crash, and looking into the code shows that rGFA is, indeed, baked in, as it were.

I am wondering if there are technical reasons rGFA is used and GFA 1.0 is not supported. This constraint prevents applying gaftools to any genomics analyses that require haplotype information, which is a pretty big limitation. Any thoughts?

**Comment by asylvz** [comment]
Hi @adadiehl , currently gaftools is dependent on rGFA and I'm not sure if we have plans to make it compatible with GFA format in the near future.

Thanks for your interest.
