### ISSUE TITLE
can not found gfa_sort function in sort.py

### ISSUE THREAD

**Issue by sdws1983** [marschall-lab/gaftools#2]
Hi,

I installed gaftools according to the process and tried to index, but found the following error:

```
$ gaftools index t.gaf t.gfa
Traceback (most recent call last):
  File "/share/home/miniconda3/envs/podman/bin/gaftools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/share/home/software/gaftools/gaftools/__main__.py", line 88, in main
    module.main(args)
  File "/share/home/software/gaftools/gaftools/cli/index.py", line 206, in main
    run(**vars(args))
  File "/share/home/software/gaftools/gaftools/cli/index.py", line 24, in run
    from gaftools.cli.sort import gfa_sort
ImportError: cannot import name 'gfa_sort' from 'gaftools.cli.sort' (/share/home/software/gaftools/gaftools/cli/sort.py)
```
How to solve?

Thanks

**Comment by samarendra-pani** [comment]
Hello,

I added the script for gfa sorting in the new commit. Give the indexing a try with the latest commit.

Regards,
Samarendra

**Comment by sdws1983** [comment]
> 

Hi Samarendra,

Thanks for your help, now I can run indexing without the above errors. But what bothers me now is how to obtain the `rgfa` format file. I tried to use the `vg convert` command but the gfa obtained does not contain the rgfa tags. I would like to ask how you generally convert it.

Many Thanks!

Yumin

**Comment by colindaven** [comment]
minigraph is the most well known tool to create rGFA format pangenomes. 

I maintain a list of software here, as there are other tools which do this too.

https://github.com/colindaven/awesome-pangenomes

**Comment by samarendra-pani** [comment]
A GFA to rGFA converter seems like a good idea. This toolkit was developed keeping the HPRC minigraph rGFA in mind. But it makes sense to make a GFA to rGFA converter to allow a broader range of utility. The converter might already exist as part of gfatools (not sure).
