### ISSUE TITLE
Improve order_gfa documentation

### ISSUE THREAD

**Issue by adadiehl** [marschall-lab/gaftools#21]
Please add complete description of output files and their content. In particular, please explain the meaning and interpretation of B0 and N0 tags relative to the following excerpt:

"...bubbles in the graphs are identified using gaftools (commit ID: 919bbecf51602161db7ba6e859cc5c26a7413c83).
The function order_gfa tags the nodes of the graph to identify whether the nodes are bubble nodes (nodes inside a bubble) or scaffold nodes (nodes outside a bubble)."

(https://www.biorxiv.org/content/10.1101/2024.04.18.590093v1.full.pdf)

**Comment by fawaz-dabbaghieh** [comment]
Thank you for your comment, Adam.
Indeed, we need to add more documentation which we are working on. In the meantime, I wrote this quick explanation on the `order_gfa` subcommand, I hope it helps [here](https://github.com/marschall-lab/gaftools/blob/parallel_realign/Docs/order_gfa.md).

**Comment by adadiehl** [comment]
Thank you, this is very helpful!
